# monitoring/prometheus-config.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
  namespace: default
  labels:
    app: prometheus
    component: server

data:
  prometheus.yml: |
    global:
      scrape_interval: 15s
    scrape_configs:
        - job_name: 'webapp-monitoring'
          static_configs:
            - targets: ['webapp-service.default.svc.cluster.local:80']
